### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#102]
Current state of ideas for logging. Before implementing it 
* https://www.highlight.io/blog/5-best-python-logging-libraries
* https://github.com/Delgan/loguru

Questions:
* Do we stick with the standard logging? https://betterstack.com/community/guides/logging/best-python-logging-libraries/#1-the-standard-logging-module
* Do we need to consider anything special for multiple processes or can they all log to the same file.
* Wo we still have some print-statements. For me this is ok. We can remove them later
* Handling of counters (e.g. ServiceJourney). Such prints could be done with a standardised function
* Any other things to consider

**Comment by ue71603** [comment]
We need our own logger (that is based on existing ones).

Some warnings are only needed once (e.g. before the corrections are made).
Should be able to work in parallel.
For specific steps files needs to be generated themselves (e.g. the list of references that are going into the blue.

**Comment by skinkie** [comment]
I think the class should register something like a list of generic warnings / errors, ideally based on some enum / numerical value. In that case the generic logger can decide upon an incoming warning / error to report it or not.

**Comment by ue71603** [comment]
PR exists
