### ISSUE TITLE
No interchanges found

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#105]
I used Swiss4.zip
[swiss4.zip](https://github.com/user-attachments/files/17147217/swiss4.zip)

It contains interchangeRules and journeyMeetings

Using

     {
    "block": "swiss4",
    "scripts": [
        {"script": "clean_tmp", "args": ["d:/aux_test_processing"]},
        {"script": "swiss_to_db.py", "args": ["d:/swiss4.zip d:/aux_test_processing/swiss-import.duckdb"]},
        {"script": "epip_db_to_db.py", "args": ["d:/aux_test_processing/swiss-import.duckdb d:/aux_test_processing/netex-database.duckdb"]},
        {"script": "epip_db_to_xml.py", "args": ["d:/aux_test_processing/swiss-import.duckdb d:/aux_test_processing/netex-database.duckdb d:/aux_test_processing/swiss3-netex.xml"]},
        {"script": "aux_assertions.py", "args": ["./aux_test_input/swiss-assertions.txt d:/aux_test_processing/swiss3-netex.xml"]},
        {"script": "aux_netex_stats.py", "args": ["d:/aux_test_processing/swiss3-netex.xml"]},
        {"script": "netex_to_db.py", "args": ["d:/aux_test_processing/swiss3-netex.xml d:/aux_test_processing/netex-database.duckdb"]},
        {"script": "related_explorer.py", "args": ["d:/aux_test_processing/netex-database.duckdb ServiceJourney random d:/aux_test_processing/sj.xml"]},
        {"script": "netex_db_to_gtfs.py", "args": ["d:/aux_test_processing/netex-database.duckdb d:/aux_test_processing/swiss3-gtfs.zip"]},
        {"script": "aux_gtfs_check.py", "args": ["d:/aux_test_processing/swiss3-gtfs.zip"]},
        {"script": "gtfs_show_map.py", "args": ["d:/aux_test_processing/swiss3-gtfs.zip d:/aux_test_processing/swiss3-map.html routes"]}
        ]
  }

it lost the interchanges and stuff. already in the swiss3-netex.xml. I guess the  epip-db-db.py omits them.  Is this something that it should do?

I then moved directly from loading to writing to GTFS
```

     {
    "block": "swiss4short",
    "scripts": [
        {"script": "clean_tmp", "args": ["d:/aux_test_processing"]},
        {"script": "swiss_to_db.py", "args": ["d:/swiss4.zip d:/aux_test_processing/swiss-import.duckdb"]},
        {"script": "netex_db_to_gtfs.py", "args": ["d:/aux_test_processing/netex-database.duckdb d:/aux_test_processing/swiss4short-gtfs.zip"]},
        {"script": "aux_gtfs_check.py", "args": ["d:/aux_test_processing/swiss4short-gtfs-gtfs.zip"]},
        {"script": "gtfs_show_map.py", "args": ["d:/aux_test_processing/swiss4short-gtfs-gtfs.zip d:/aux_test_processing/swiss4short-gtfs-map.html routes"]}
        ]
    }
    ,


```

No, also no transfers

Pls inform me, when this works.

**Comment by skinkie** [comment]
Did you use the last version, pushed yesterday? That covers the export and import for GTFS. In all other cases I'll check at what part we lose them.

**Comment by ue71603** [comment]
Update from master says, no updates needed on the branch I am working on :-(

**Comment by skinkie** [comment]
If you are using your own branch, you need to merge main into it.

**Comment by ue71603** [comment]
That's what update from master is doing...I am up to date with master.

**Comment by skinkie** [comment]
Then leave it assigned to me. I was quite sure we had transparent interchanges now. 

https://github.com/skinkie/reference/blob/master/gtfs-netex-test/epip_db_to_xml.py#L221

**Comment by ue71603** [comment]
thanks

**Comment by ue71603** [comment]
blocked until https://github.com/skinkie/reference/issues/145 is fixed

**Comment by ue71603** [comment]
Retested with the current pipeline. No InterchangeRule found .  Processing steps see: https://github.com/skinkie/reference/issues/170

Tested with swiss4-netex.xml (EPIP conversion)

**Comment by skinkie** [comment]
@ue71603 is the interpretation of this issue that you want swiss to gtfs, and in gtfs you don't see transfers.txt? _Or_ is this about epip?

**Comment by ue71603** [comment]
I didn't see them in epip. But again. May relate to the other problem and bases on a very old version. Would have tested it again, if I could create  an EPIP;-)

**Comment by ue71603** [comment]
duplicates #199
