### ISSUE TITLE
The importer should notice, if they can process the stuff

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#107]
swiss_to_db.py should stop, when it can't process the xml presented (we need also a definition, for what it should be used).

ditto for netex_to_db.py (and others).

When must epiip_db_to_db be used?

**Comment by skinkie** [comment]
So first it must know it is in fact a Swiss file. But the Swiss files do not have any TypeOfFrameRef. Hence there must be an identification. Any suggestions? Look for files based on the filename?

With respect to your second question, isn't that the path after you have imported and converted a gtfs, then to produce epip?

**Comment by ue71603** [comment]
It really should be used only for Swiss data?  We could check for the ch:1 start of ids. Then it is clear.


2nd part: so epip_db_to_db is only used in connection with gtfs_to_db?  I never use it if I load swiss netex and then want to store epip? I can always do this direct?

Here the (missing) architecture diagrams would help a lot :-)

**Comment by skinkie** [comment]
> It really should be used only for Swiss data? We could check for the ch:1 start of ids. Then it is clear.

Sure.

> 2nd part: so epip_db_to_db is only used in connection with gtfs_to_db? I never use it if I load swiss netex and then want to store epip? I can always do this direct?

The db-to-db exists to rewrite the concepts found in the source data into the concepts used in the target dataset. If the origin and destination profiles are very similar, it can do without. But in general the db-to-db cannot be omitted.

**Comment by ue71603** [comment]
so is epip_db_to_db.py useful only for GTFS -> EPIP or also for   Swiss NeTEX -> EPIP?

**Comment by skinkie** [comment]
It should always be executed, unless the input profile is the same.

**Comment by skinkie** [comment]
dutch_to_db.py now has a TypeOfFrame filter example. Since there is no epip_to_db.py yet, it has not been changed yet. For a specific profile the supported TypeOfFrameRef could be set, the importer will then only import the known parts.
