### ISSUE TITLE
Swiss conversion

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#11]
.... I am not sure that you write with the right encoding:
![image](https://github.com/skinkie/reference/assets/24227470/c40c614a-f9e5-4456-9c88-1264de6a0fcb)

Zürich doesn't look that good.

**Comment by skinkie** [comment]
Like mentioned in the code. DuckDB only handles UTF-8.

**Comment by ue71603** [comment]
XML spy is complaining that it is not utf-8. I have a look

**Comment by ue71603** [comment]
see #12
