### ISSUE TITLE
Create a gtfs_db_to_db?

### ISSUE THREAD

**Issue by skinkie** [skinkie/reference#133]
At this point it is suggested that netex_to_gtfs could directly create GTFS output, but many things such as the projection to WGS84 projection, or transforming the timetabled passing times / calls have not been done. This is a difficult topic, it shouldn't to be required to completely expand (and materialise) all timetables, on the other hand, the way the gtfs export is now written it assumes passing times. Hence EPIP / Nordic would be the minimum thing to have.

So either have the facade to accept any concept or agree to always require a preprocessing step. There is no reason that the facade cannot accept everything. We just must not do it in every export option.

TODOs in the file:
- Put stuff that is in responsibilitySet into OperatorRef (in Switzerland it is the Authority to put there, but we can discuss it)
- Doing some projections
- Do we do the passing time stuff already?  For Switzerland. Do you propose  use Swiss -> EPIP -> GTFS?

**Comment by ue71603** [comment]
Isthis a 1.0 story?

**Comment by ue71603** [comment]
Can we start to compile the list of stuff the gtfs_db_to_db should do in the description (this issue)?

**Comment by skinkie** [comment]
Answer is yes. Introduction of shapes.txt remaining for now.
