### ISSUE TITLE
Operator may not be defined at Line level

### ISSUE THREAD

**Issue by skinkie** [skinkie/reference#134]
The GTFS profile currently assumes that an OperatorRef exists at Line level, it is already capable of handling branding_ref or authority_ref instead, but it is not capable of resolving this data from a ResponsibilitySet, OperatorView (at TimetableFrame) or as an aggregate from ServiceJourney[]/OperatorRef. 

A preprocessing step, as suggested in #133 may take care of this, hence if no OperatorRef is found at Line level, it should search for it.

**Comment by ue71603** [comment]
We rely heavility on ResponsibilitySet so we would be happy, if the system can take care. Whether in a db_to_db or a different step, can be discussed. Or do you suggest a tool_resolve_responsibility_set.py?

**Comment by skinkie** [comment]
GTFS expect a relationship between Line and Operator. In some step this must be resolved. Therefore I suggested #133 to assure that the GTFS requirements are met, and not 'on the fly' calculated. It is too big of hassle to maintain, if we do it for other parts.

**Comment by ue71603** [comment]
Wedo this  in #133

**Comment by skinkie** [comment]
@ue71603 the problem with aggregating these issues is that we end up with a big issue that is not a single feature. While for a proper overview a single feature description is important. I think even for EPIP this feature is important.

**Comment by ue71603** [comment]
But this still means that gtfs_db_to_db.p needs to be created? or where do you want to store it?
You can also go ahead and to it either in gtfs_db_to_db.py or in one of the other scripts.

**Comment by skinkie** [comment]
I think this specific thing "aggregate operators to line" is a transformer. We need that transformer in GTFS and EPIP.

**Comment by ue71603** [comment]
I abide to your wisdom.

**Comment by skinkie** [comment]
We have one exception case. If operator_ref is only defined at ServiceJourney level, we are currently not projecting it back to a line instance. It has more nasty side effects, for example a line executed with two operators should be two different lines (routes) in GTFS.
