### ISSUE TITLE
Direction missing

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#143]
[swiss_mikro.zip](https://github.com/user-attachments/files/17416062/swiss_mikro.zip)

block
[{
    "block": "swissmikro",
    "scripts": [
        {"script": "clean_tmp", "args": "%%dir%%"},
        {"script": "gtfs_import_to_db.py", "args": "./aux_test_input/swiss_mikro.zip %%dir%%/gtfs-import.duckdb --log=%%log%% "},
        {"script": "gtfs_convert_to_db.py", "args": "--log=%%log%% %%dir%%/gtfs-import.duckdb %%dir%%/netex-import.duckdb"},
        {"script": "epip_db_to_db.py", "args": "--log=%%log%% %%dir%%/netex-import.duckdb %%dir%%/netex-database.duckdb"},
        {"script": "epip_db_to_xml.py", "args": "--log=%%log%% %%dir%%/netex-import.duckdb %%dir%%/netex-database.duckdb %%dir%%/%%block%%-netex.xml"},
        {"script": "tool_netex_stats.py", "args": "--log=%%log%% %%dir%%/%%block%%-netex.xml"},
        {"script": "netex_to_db.py", "args": "--log=%%log%% %%dir%%/%%block%%-netex.xml %%dir%%/netex2-database.duckdb"},
        {"script": "related_explorer.py", "args": "%%dir%%/netex2-database.duckdb ServiceJourney random %%dir%%/sj.xml"},
        {"script": "related_explorer.py", "args": "%%dir%%/netex2-database.duckdb Line random %%dir%%/line.xml"},
        {"script": "netex_to_db.py", "args": "--log=%%log%% %%dir%%/sj.xml %%dir%%/netex3-database.duckdb"},
        {"script": "epip_db_to_db.py", "args": "--log=%%log%% %%dir%%/netex3-database.duckdb %%dir%%/netex4-database.duckdb"},
        {"script": "epip_db_to_xml.py", "args": "--log=%%log%% %%dir%%/netex3-database.duckdb %%dir%%/netex4-database.duckdb %%dir%%/%%block%%-sj-netex.xml"}
        ]
  },](url)

can be executed fr
om logging branch:
`python tool_script_runner.py ./scripts/scripts_regression.txt run.log swissmikro
`
swissmikro-sj-netex.xml is not valid.
`
The <keyref> identity constraint 'Direction_KeyRef' did not match within the scope of element <PublicationDelivery>. The referenced identity constraint 'Direction_AnyVersionedKey' is out of scope.`

Had to add:```

				</SiteFrame>
				<ServiceFrame id="EU_PI_NETWORK" version="20241017">
					<TypeOfFrameRef ref="epip:EU_PI_NETWORK" versionRef="1.0"/>
					<directions>
						<Direction id="OPENOV:Direction:outbound" version="any"/>
					</directions>
					<lines>
						<Line id="SBB:Line:92-801-A-j24-1" version="20241010">
							<Name/>

```

Can you check, why Direction was not done correctly.

**Comment by ue71603** [comment]
will retest with pickle version

**Comment by skinkie** [comment]
@ue71603 works for me.

**Comment by ue71603** [comment]
for me too
