### ISSUE TITLE
Problem with encoding

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#144]
In gtfs-import_to_db you use handle_file which uses auto-detection. For siwssmirko it fails for trips. It assumes the wrong one.
I would prefer we assume UTF-8 for everything.  for stops.txt it worked fine.

https://github.com/user-attachments/files/17416062/swiss_mikro.zip

![image](https://github.com/user-attachments/assets/f39c8a80-1a31-4428-9888-e354bfc8ab9d)
![image](https://github.com/user-attachments/assets/7aa040b7-98d7-444c-8734-bbae1cf9fac2)

**Comment by ue71603** [comment]
trips.txt

```
route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,block_id
"91-11-O-j24-1","TA+8f0e0","13.TA.91-11-O-j24-1.30.R","Bern","4556","1",""
"92-801-A-j24-1","TA+ywk10","10.TA.92-801-A-j24-1.58.H","Frauenfeld, Bühl","41871","0","15612"

```
doesn't tripper detector in a good way.

**Comment by skinkie** [comment]
What is the source file for it?

**Comment by ue71603** [comment]
swissmikro as attached. trips.txt is the problematic one.

**Comment by ue71603** [comment]
the spec says GTFS = UTF-8: https://gtfs.org/documentation/schedule/reference/#document-conventions

**Comment by skinkie** [comment]
@ue71603 the question is not what the output is. The question is, what was the **original** input that Swiss mikro was used to create.

**Comment by ue71603** [comment]
This is original. Although the trips.txt was created by hand.  But it still is UTF-8 in my view.

**Comment by ue71603** [comment]
The zip is the input.

**Comment by skinkie** [comment]
I'll do the analysis.

**Comment by ue71603** [comment]
Currently I didn't see it.
