### ISSUE TITLE
processing one of the latest Swiss NeTEx iles

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#149]
I used one of the latest swiss NeTEx files: https://opentransportdata.swiss/de/dataset/timetablenetex_2024

and finally have it in a linux virtualbox with acceptable speed.

Working on the new_logging branch.

After 2-3 hours I got

![image](https://github.com/user-attachments/assets/6d1c17fc-e8aa-49df-949e-0159d3133c5f)

can you check?

**Comment by ue71603** [comment]
adding netex_monkeypatch doesn't work. as this gets a circular import

**Comment by skinkie** [comment]
Is this the main branch?

**Comment by ue71603** [comment]
I will. But then I would like for the branches to be merged.

**Comment by ue71603** [comment]
Worked on main branch. I then cleaned the new_logging branch. Seems to work there now too
