### ISSUE TITLE
Can I test a conversion swiss netex 2 epip already?

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#15]
with which subelement?

**Comment by skinkie** [comment]
I think swiss netex is calls, hence it might be that the GTFS one _could_ work.

**Comment by ue71603** [comment]
any-to-epip.py.
you read a gz. Is this a single file xml?  The Swiss file is separated by Frame. Does this need preprocessing? and do you have a .py that does that already?

**Comment by ue71603** [comment]
This would be some building blocks for the pipeline.

**Comment by ue71603** [comment]
Can it be that any-to-epip is very minimalistic? It doesn't copy ResourceFrame it seems. Also. I didn't see anyhwere where it should take the Call and do something with it.

**Comment by skinkie** [comment]
> any-to-epip.py. you read a gz. Is this a single file xml? The Swiss file is separated by Frame. Does this need preprocessing? and do you have a .py that does that already?

Because it reads an xpath expression, it does not consider frames, just the instances of the objects. This is a potential issue if the frame defaults are different. Hence the frame defaults might have to be applied first. But I have not found a complex case yet that mixes frame defaults.

> Can it be that any-to-epip is very minimalistic? It doesn't copy ResourceFrame it seems. Also. I didn't see anyhwere where it should take the Call and do something with it.

Magic happens here:
```python
    timetabledpassingtimesprofile = TimetablePassingTimesProfile(codespace, version, service_journeys, service_journey_patterns)
    timetabledpassingtimesprofile.getTimetabledPassingTimes(clean=True)
```

**Comment by ue71603** [comment]
And how to deal with the frame based files: https://opentransportdata.swiss/de/dataset/timetablenetex_2024/resource/7faba8f2-797f-41f8-81e6-d8b3f55e9e85
collate some manually for testing?  
write a collator?

**Comment by skinkie** [comment]
You mean Line based deliveries + shared file like Norway?

**Comment by ue71603** [comment]
We have a COMMON, RESOURCE, SERVICE, SERVICECALENDAR,SITE file and then linebased TIMETABLE.

**Comment by skinkie** [comment]
Yes, in that case you would need to heuristically establish which files you want to load to fetch the concept. But as long you could lazy load them, it is not an issue.

One of the other things I would like to implement is actual lazy loading. So that concepts can be resolved 'just in time'.

**Comment by ue71603** [comment]
Lets assume our case:   the pool to be loaded would be the  COMMON, RESOURCE, SERVICE, SERVICECALENDAR,SITE  and then the timetable can be processed each.  So how to do more parameter:
- mustinputfiles (here COMMON, RESOURCE, SERVICE, SERVICECALENDAR,SITE)
- processfiles (here TIMETABLE)
- outputfilefolder
-  exportmode: singleFile, independentOutputFiles, sameStructure ?

**Comment by ue71603** [comment]
currently any-to-epip is doing file by file work.

**Comment by skinkie** [comment]
> currently any-to-epip is doing file by file work.

Correct, only the Nordic export (not-validated) is splitting file. The big question is: should the separate files be loaded in for example a database first (this would allow resolving interfile relationships), or do we blissfully ignore those, and just go directly for a Linebased-to-Linebased conversion.

**Comment by ue71603** [comment]
Would need 2-3 GB in memory, when we load them beforehand.  As for a database => you are the architect.

**Comment by ue71603** [comment]
probably also outdated.
