### ISSUE TITLE
pickle performance improvement

### ISSUE THREAD

**Issue by skinkie** [skinkie/reference#158]
2344 ScheduledStopPoints, stored in pickle format (highest protocol), then queried. First is pickle, second is xml.
```
2344
0.6774206161499023

real    0m8.590s
user    0m8.237s
sys     0m1.191s

2344
1.5347440242767334

real    0m9.560s
user    0m9.029s
sys     0m1.337s
```

There are some things like embeddings and references which must be fixed too. Ideally I would be able to switch this dynamically.

**Comment by ue71603** [comment]
to be closed?
