### ISSUE TITLE
Decide (for EPIP) how to prioritise Line/OperatorRef over Line/AuthorityRef

### ISSUE THREAD

**Issue by skinkie** [skinkie/reference#161]
EPIP at this point supports either Line/OperatorRef or Line/AuthorityRef. The goal obviously is to show the value that would makes the most sense. But but can be defined now, there is currently also the option of "additionalOperators". Closely related to #134

**Comment by ue71603** [comment]
In Switzerland AuthorityRef is more important. But I don't know if still open. additionalOperators can then be the OperatorRef.
@skinkie

**Comment by skinkie** [comment]
@ue71603 then make it configurable in the options.
