### ISSUE TITLE
GTFS not valid after conversions

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#170]
Two errors occured in processing swiss4 in the validation on mobilitydata:
* References to stop wrong
* Date handling problematic

See report: https://gtfs-validator.mobilitydata.org/?report=1cb302da-4c7e-406b-8c2e-39e1857dd41f

Relevant file:  [swiss4.zip](https://github.com/user-attachments/files/18036331/swiss4.zip)

processing (now you can do it as well, after changing the relevant folders in configuration.py or local_configuration.py
and the input folder for swiss4 in scripts/scripts_regression.txt

script to run: python tool_script_runner.py ./scripts/scripts_regression.txt run.log swiss4

and then having a look at swiss4-gtfs.zip

**Comment by ue71603** [comment]
I can send you swissmikro...  or we do related_explorer. however, at least on my machine and trying to extract stuff from swiss4 it is very very slow currently.

**Comment by ue71603** [comment]
But swissmikro is a gtfs file in it origin.

**Comment by skinkie** [comment]
Still, I am shocked by the poor performance of even loading the file.

**Comment by ue71603** [comment]
[swiss_mikro.zip](https://github.com/user-attachments/files/18043532/swiss_mikro.zip)
so not everything can be tested.. it is in the regression_suite, but  the gtfs loading also has a bug https://github.com/skinkie/reference/issues/173.. perhaps that one first?

**Comment by ue71603** [comment]
I just started with swiss4, because their were old issues related to it.

**Comment by ue71603** [comment]
> Still, I am shocked by the poor performance of even loading the file. That having said: the DuckDB is already 1GB in size.

with pickle? Or something I did?   Other small question. If is start redoing logging (a) wait a bit until the things are better, (b) do it in a new branch?  I intend to simplify it and using more basic functions. This should make it more robust and also allow to use it in  the generators..

**Comment by skinkie** [comment]
> > Still, I am shocked by the poor performance of even loading the file. That having said: the DuckDB is already 1GB in size.
> 
> with pickle? 

It was doing the 'new-old reference code'. I have disabled that now and hope that the new-new reference code may be faster. We must benchmark that.

> Other small question. If is start redoing logging (a) wait a bit until the things are better, (b) do it in a new branch? I intend to simplify it and using more basic functions. This should make it more robust and also allow to use it in the generators..

Check my last commit. Everywhere there is a "Database" object, you can have db_read.logger or db_write.logger. If you assign the same logger to both, it is always available. I am now 'abusing' the database object as _context_.

**Comment by ue71603** [comment]
new mikro for you (without errors)
[swiss_mikro.zip](https://github.com/user-attachments/files/18044081/swiss_mikro.zip)

**Comment by ue71603** [comment]
The swiss4 regression still does not provide a valid GTFS: CH XML -> EPIP XML  -> GTFS. calendar missing see: https://gtfs-validator-results.mobilitydata.org/3fd0cf85-26e4-465d-97a7-60805da3189a/report.html


swiss_mikro also doesn't provide calendars. in gtfs
With what do you test this?

**Comment by ue71603** [comment]
I close this one and open new ones, if necessary. It seems that the problems shifted
