### ISSUE TITLE
Export with related_explorer not a valid XML

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#180]
[sj.zip](https://github.com/user-attachments/files/18052742/sj.zip)

Script see here: https://github.com/skinkie/reference/issues/179

* DayTypeRef without DayTye
    ![image](https://github.com/user-attachments/assets/8ea90d60-4cf6-4ee5-aecc-322232fe5850)

* JourneyPattern not exported
   e.g. <ServiceJourneyPatternRef version="20241010" ref="OPENOV:ServiceJourneyPattern:7e19303d"/>

* Line not exported

* StopPointInServicePattern not exported.

(and here I stopped testing). I would expect related_explorer to provide a valid xml.

**Comment by skinkie** [comment]
@ue71603 is the output of epip_db_to_xml.py first time you run it a valid file?

**Comment by skinkie** [comment]
@ue71603 please recheck.

**Comment by ue71603** [comment]
EPIP export was valid after the first steps
```

    "scripts": [
        {"script": "clean_tmp", "args": "%%dir%%"},
        {"script": "gtfs_import_to_db.py", "args": "d:/input/swiss_mikro.zip %%dir%%/gtfs-import.duckdb --log=%%log%% "},
        {"script": "gtfs_convert_to_db.py", "args": "--log=%%log%% %%dir%%/gtfs-import.duckdb %%dir%%/netex-import.duckdb"},
        {"script": "epip_db_to_db.py", "args": "--log=%%log%% %%dir%%/netex-import.duckdb %%dir%%/netex-database.duckdb"},
        {"script": "epip_db_to_xml.py", "args": "--log=%%log%% %%dir%%/netex-import.duckdb %%dir%%/netex-database.duckdb %%dir%%/%%block%%-netex.xml"},
```

However, after loading and exporting to related_explorer.py: No longer valid. Really only ServiceJourney exported and no related elements at all.


```
       {"script": "netex_to_db.py", "args": "--log=%%log%% %%dir%%/%%block%%-netex.xml %%dir%%/netex2-database.duckdb"},
        {"script": "related_explorer.py", "args": "--log=%%log%% %%dir%%/netex2-database.duckdb ServiceJourney random %%dir%%/sj.xml"},

```

**Comment by skinkie** [comment]
It seems that you are running  a version which does not have the referencing table (or that table is empty).

**Comment by ue71603** [comment]
you see the scripts I use.  So I will have to laod it with --referencing always?

**Comment by skinkie** [comment]
> you see the scripts I use. So I will have to laod it with --referencing always?

--referencing is removed, it will now always do it at the end of the initial import.

**Comment by skinkie** [comment]
I am positive you can test this and have a positive result.

**Comment by ue71603** [comment]
I get valid exports now.
