### ISSUE TITLE
swissmikro: EPIP export has valid UTF-8 handling

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#185]
Loading with netex_to_db.py and the using related_explorer.py doesn't handle the utf-8 properly
       {"script": "netex_to_db.py", "args": "--log=%%log%% %%dir%%/%%block%%-netex.xml %%dir%%/netex2-database.duckdb"},
        {"script": "related_explorer.py", "args": "--log=%%log%% %%dir%%/netex2-database.duckdb ServiceJourney random %%dir%%/sj.xml"},
 
[swissmikro-netex.zip](https://github.com/user-attachments/files/18065984/swissmikro-netex.zip)

![image](https://github.com/user-attachments/assets/1b9aba74-68ef-4edc-be9d-ede15ecd61dc)

**Comment by skinkie** [comment]
![image](https://github.com/user-attachments/assets/e4733154-8ccb-4f70-a158-40303508bd8e)

So this is already wrong in EPIP XML, and likely already wrong in GTFS.

**Comment by ue71603** [comment]
You were right. trips_txt was not UTF-8. Switched it to utf-8 BOM
