### ISSUE TITLE
XSD validation

### ISSUE THREAD

**Issue by skinkie** [skinkie/reference#208]
If you want this, I would say that it should be a submodule of the project. That would also allow the xsdata code to run on that specific version.
```
OSError: Error reading file 'C:/Users/ue71603/MG_Daten/github/NeTEx1/xsd/netex_publication.xsd': failed to load external entity "C:/Users/ue71603/MG_Daten/github/NeTEx1/xsd/netex_publication.xsd"

2024-12-17 17:15:32,229 - script_runner - ERROR - Error reading file 'C:/Users/ue71603/MG_Daten/github/NeTEx1/xsd/netex_publication.xsd': failed to load external entity "C:/Users/ue71603/MG_Daten/github/NeTEx1/xsd/netex_publication.xsd": Traceback (most recent call last):
```

**Comment by ue71603** [comment]
I will optimise it :-) Did it already at a different place. I will on the fly download the xsd and use it to validate.

**Comment by skinkie** [comment]
On the fly downloading might not be what the user expects.

**Comment by ue71603** [comment]
they need to be suprised....

**Comment by ue71603** [comment]
So you want the XSD materialized in a checked out project?

**Comment by skinkie** [comment]
`git submodule add -b next https://github.com/NeTEx-CEN/NeTEx.git NeTEx`

**Comment by ue71603** [comment]
you always want to use your submodules :-)

**Comment by ue71603** [comment]
fixed with 3b30b83fb6c8d68f4f676f729d77f8bb5247f82a

**Comment by skinkie** [comment]
@ue71603 Please change he path to NeTEx or NeTEx.xsd (and not xsd). And documentation update so the user is suggested to do the git submodule init and git submodule update round.

**Comment by ue71603** [comment]
you suggested netex, but you used up that folder already.

**Comment by skinkie** [comment]
> you suggested netex, but you used up that folder already.

Actually on my operating system the file system is case sensetive ;-)

**Comment by ue71603** [comment]
I will rename all folders to variantes of NeTEx, NETEX, neTex or use special characters for the X:
![image](https://github.com/user-attachments/assets/b508beb6-0ef0-45b6-9144-5d9c8ac871ee)
