### ISSUE TITLE
Problem with LxmlTreeSerializer

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#27]
* Did download the repoxistory xsdata
* Did set it to your PR
* Dip pip install .
* Did  pip install .[cli,soap,lxml]
* Did run import.py
* Did run any-to-epi.py
Got this errormessage: 
C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\venv\Scripts\python.exe C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\any-to-epip.py 
Traceback (most recent call last):
  File "C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\any-to-epip.py", line 10, in <module>
    from xsdata.formats.dataclass.serializers import XmlSerializer, LxmlTreeSerializer
ImportError: cannot import name 'LxmlTreeSerializer' from 'xsdata.formats.dataclass.serializers' (C:\Users\ue71603\MG_Daten\github\reference\gtfs-netex-test\venv\Lib\site-packages\xsdata\formats\dataclass\serializers\__init__.py)

**Comment by skinkie** [comment]
I can reproduce it.

Behavior changed in: https://github.com/tefra/xsdata/commit/510b2b93051203e76f9bc3770784c386879c2302

LxmlTreeSerializer should become TreeSerializer.

**Comment by ue71603** [comment]
So, the program is not et adapted to the new TreeSerializer.

Perhaps you should remove stuff that is no longer working.
It is e.g. not clear to me, which things one should still use. The programs using duckdb, I guess not.

**Comment by ue71603** [comment]
I already use the new xsdata in my view.

**Comment by skinkie** [comment]
Pushed and resolved.
