### ISSUE TITLE
new program sequences

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#29]
Which sequences of py do I need to run for:

any NeTEx  --> EPIP

Was:
  - any-to-epip.py

GTFS --> NeTEx
Was:
  - import.p
  - GtfsNeTEx.py

GTFS --> EPIP.
???

I

**Comment by ue71603** [comment]
You sent it in the meail.Still wasn't able to figure it out for gtfs.
* gtfs_import_to_db.py gives me a duckdb.
* gtfs_db_to_db.py writes from and to a duckdb.
* gtfs_convert_to_db.py also works with duckdb.
* import.py gives me a duckdb.
* db_to_db.py wants an sqlite d to work from. .


My questions:
* Is that pipeline already operational? and if yes:
  * If I want to convert the flixbus.gtfsfrom https://transport.data.gouv.fr/datasets/flixbus-horaires-theoriques-du-reseau-europeen-1  into an EPIP,which program do I need to run in what sequence?
* Are the anyxxx.py still relevant?
* when to use the *new*.py files?

**Comment by ue71603** [comment]
swiss_db_to_db.py seems not be finished. I try using db_to_db.py. I hope it is ok.

**Comment by skinkie** [comment]
db_to_db is for epip

**Comment by skinkie** [comment]
README.md is updated, currently validating the swiss import flow.
