### ISSUE TITLE
import.py as mentioned in README.md does no longer exist.

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#31]
Is the example valid?

**Comment by skinkie** [comment]
My README.md does not have import.py ;-)

**Comment by ue71603** [comment]
it is on  https://github.com/skinkie/reference. But I will work now with the README.md from https://github.com/skinkie/reference/tree/master/gtfs-netex-test

**Comment by skinkie** [comment]
For production I want it in PyNeTExConv anyway.

**Comment by ue71603** [comment]
no worries... if ou poin tto to the right place...URL
