### ISSUE TITLE
epip_db_to_db.py lost most of the journeys. Only retained 25 ServiceJourney for Flixbus

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#34]
executed the steps
python gtfs_import_to_db.py C:/Users/ue71603/MG_Daten/conversion/flixbus/flixbus.zip  C:/Users/ue71603/MG_Daten/conversion/flixbus/gtfs-import.duckdb
python gtfs_convert_to_db.py C:/Users/ue71603/MG_Daten/conversion/flixbus/gtfs-import.duckdb C:/Users/ue71603/MG_Daten/conversion/flixbus/netex-import.duckdb
python epip_db_to_db.py C:/Users/ue71603/MG_Daten/conversion/flixbus/netex-import.duckdb C:/Users/ue71603/MG_Daten/conversion/flixbus/netex-import-epip.duckdb
python epip-db-to-xml.py C:/Users/ue71603/MG_Daten/conversion/flixbus/netex-import.duckdb C:/Users/ue71603/MG_Daten/conversion/flixbus/netex-import-epip.duckdb C:/Users/ue71603/MG_Daten/conversion/flixbus/netex.xml.gz
del C:/Users/ue71603/MG_Daten/conversion/flixbus/*.duckdb

Used the latest Flixbusdata

input:
Line 1113
Codespace 1
Version 1
Operator 2
ScheduledStopPoint 2195
StopPlace 2195
PassengerStopAssignment 2195
AvailabilityCondition 35391
 ServiceJourney 32330

output:
epip_line_memory
Line 1113
epip_scheduled_stop_point_memory
ScheduledStopPoint 2195
epip_site_frame_memory
PassengerStopAssignment 2195
StopPlace 2195
 ServiceJourney 35

**Comment by ue71603** [comment]
Had it run in pycharm terminal.  I did not regenerate with xsdata generate -c netex.conf /path/to/NeTEx/xsd/NeTEx_publication.xsd
I just used the latest update from your master.

**Comment by skinkie** [comment]
Was fixed by d0bd2f126d1542ad248e3506c4218ac59e170055
