### ISSUE TITLE
blablacar bus did not have a feed_end_date => program stopped

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#35]
Is this your expected outcome? 
If yes, then we will have to specify, that we really need a full feed_info.txt.

**Comment by ue71603** [comment]
However, gtfs_import_to_db went smoothly. the error occured in gtfs_convert_to_db

**Comment by skinkie** [comment]
> However, gtfs_import_to_db went smoothly. the error occured in gtfs_convert_to_db

Want to test it.

**Comment by ue71603** [comment]
updated feed_end_date. then it worked

**Comment by ue71603** [comment]
[gtfs.zip](https://github.com/user-attachments/files/16099794/gtfs.zip)

**Comment by ue71603** [comment]
..already with updated feed_info.txt  (was missing the last column originally (header and data column)

**Comment by ue71603** [comment]
was: [feed_info.txt](https://github.com/user-attachments/files/16099806/feed_info.txt)

**Comment by skinkie** [comment]
So it was feed_info, but in this case with missing values. I would then say we must update this function, so it can add the missing recommended values. https://github.com/skinkie/reference/blob/master/gtfs-netex-test/gtfs_import_to_db.py#L159C27-L160C1
