### ISSUE TITLE
epip_db_to_xml_single_journey.py would be a great extension

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#39]
One can indicate an id of a ServiceJourney and the syystem exports that ServiceJourney with all attached data. Would allow for inspection.

**Comment by ue71603** [comment]
python epip_db_to_xml_single_journey.py  db1.duckdb   db2.duckdb  res.xml.   ch:1:sjyid:12313.2312 (or so)

**Comment by skinkie** [comment]
This would require knowing all the semantics of NeTEx (practically all the Refs, and where they lead too). This will be required in the future. So you would need to know that ServiceJourneyPatternRef pulls in ServiceJourneyPattern, which pulls in Direction and so on.

**Comment by skinkie** [comment]
For now we go for the naive, maybe we can do everything without XPath, and fully in Python objects way.

```
related_explorer.py /home/netex/netex-blabla.duckdb ServiceJourney BB:ServiceJourney:1002320289
```
