### ISSUE TITLE
Discuss how related_explorer should resolve inward objects

### ISSUE THREAD

**Issue by skinkie** [skinkie/reference#43]
It is obivously that if a ServiceJourney/LineRef exists, the user wants to see the Line too. The user is not interested in all other items that point to that line. Some objects in NeTEx only have inwards references such as NoticeAssignmentInFrame, the user _may_ be interested it the NoticeAssignment towards the ServiceJourney. This would then resolve the Notice.

We cannot do a general all Ref resolving pattern, since an DataSourceRef would resolve the DataSource and thereby _everything_ in that delivery. Discuss which special cases we must investigate, and how to find them.

**Comment by skinkie** [comment]
@ue71603 ^^^

**Comment by skinkie** [comment]
I would prefer to go through the recursive refs. That tree can be 'relatively easily and fast' be build based on all the previous work done. But it those things also asume that the source data should know what it was doing. Or it must fall back into a search for an id in _all tables_.

**Comment by ue71603** [comment]
Improvements for related_explorer.py.
* After first run through
* Add als PassengerStopAssignments where ScheduledStopPointRef is nn  the processed list and expand StopPlace, Quay and BoardingPosition recursively.
* DayTypeAssignment: where DayTypeRef is in the list and process

**Comment by skinkie** [comment]
@ue71603 more examples are JourneyMeeting, InterchangeRules.

**Comment by skinkie** [comment]
We now have embedded and referencing tables. Related explorer is capable of resolving inward references of the subject. It is technically possible to release the filter object and set it to "False" this will allow to find all inward references (to any object) in included.
