### ISSUE TITLE
In the datapipeline: the existence of files needs to be checked, if they are to be read.

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#51]

**Comment by skinkie** [comment]
Can you elaborate?

**Comment by ue71603** [comment]
One of the errors that I had was when I tried to laod a duckdb that did not exist. This did not result in a "file not found", but in an error when the generator returned none.  So it was unclear that this resultated from a missing file and not some missing data in the file.

**Comment by skinkie** [comment]
Oh right, because a non-existing file would mean create the file. I think it would also be a best practise to open it for read only (I thought I already implemented that).

**Comment by ue71603** [comment]
yes. it is onl a problem for the db that should contain the data.

**Comment by ue71603** [comment]
if you did, then close the issue.

**Comment by skinkie** [comment]
I'll explicitly add something. I think I would like to integrate #45 in this process. To make the database access as transparant as possible.

**Comment by ue71603** [comment]
you are the developer :-)
