### ISSUE TITLE
Questions concering Swiss transformation

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#61]
- Why is the DestinationDisplay "ch:1:DestinationDisplay:2851" exported, when it is not used?  No check for that?
- where do the &lt; and &gt; come from: `<ServiceJourney id="ch:1:ServiceJourney:&lt;NoGlobalID&gt;_93007_.j24_10" version="any" responsibilitySetRef="ch:1:ResponsibilitySet:BRB_104_BRB">` (also in other id (TimetabledPassingTime)
- ref="OPENOV:StopPointInJourneyPattern:bc2811b2-3"   where does the OPENOV come frome? Which field would I need to change?
- Why did you add a ValidBetween on the Line?

**Comment by skinkie** [comment]
1. The problem is that we cannot check refs, unless we know where they are. Due to how NeTEx is modelled using keyrefs, nothing is actually a relationship, just a constraint. If we would know where refs are (basically a reverse index of possible positions in an object) we could do it. An alternative way would be to do XPath expressions. Since I did implement Line based exports, it is certainly not impossible to find all the relationships. But your question was different: why is an object exported which is not in use.
2. The source data.
3. This is something that we still need to do in a more robust way. You can find the `generator_defaults` in my ideal world FrameDefaults would have everything.
4. Did I? :-)

**Comment by ue71603** [comment]
3. we would need a list of things to define in FrameDefaults....

4. It was in the source. But why? why?

**Comment by ue71603** [comment]
2. yep.

**Comment by skinkie** [comment]
keyList and Extensions are not EPIP :-)

**Comment by ue71603** [comment]
But they are also not forbidden in EPIP... At least the keyList I think we need (especially for an European stop registry). Where else should we store all the equivalent id....

**Comment by skinkie** [comment]
You _really_ don't want this. You want a stop registry from the source data. And apply the EU-stopregistry to the EPIP-export.

**Comment by ue71603** [comment]
They weren't able to do a stop registry right for the last 100 years, so I am confident that they mess this up for the next 100 too. 

There always will be multiple identifications. Where do you want to put those? Int <privateCodes> only available for NeTEx 2.0 and also not EPIP)?

In  the current situation having a copy of keyList is certainly not a bad thing in my view (otherwise why would they have modeled this on DataManagedObject

**Comment by skinkie** [comment]
In my perspective EPIP should be _as clean and as lean_ as possible. Using it as an intermediate integration step does not make sense.

**Comment by ue71603** [comment]
here not happy.... then the way you store information from keyList must be different for Switzerland.  It must be the soid if available. and it doesn't always exist. So logic is needed as well. In which of the steps do you want to build it in?

**Comment by ue71603** [comment]
If I can't express what I need to express in EPIP, then it is another completly useless format (well, that was my opinion already back then when it was created).

**Comment by skinkie** [comment]
Lets discuss tomorrow

**Comment by ue71603** [comment]
will do and then i go swimming in the river: https://aaremarzili.info/#!/

**Comment by skinkie** [comment]
> will do and then i go swimming in the river: https://aaremarzili.info/#!/

Nothing beats https://www.zwembadkessel.nl/

**Comment by ue71603** [comment]
The ValidBetween for Lines is a very special export for Line (valid only one year). Laurent wants it that way.
