### ISSUE TITLE
Related explorer did not work properly with for a random ServiceJourney (based on swiss3.zip)

### ISSUE THREAD

**Issue by ue71603** [skinkie/reference#85]
Not working were:
* It copied Line/Operator twice
* It didn't write out DayTypeRef

Can you check, why this happens?

Data
[swiss3.zip](https://github.com/user-attachments/files/16982794/swiss3.zip)

Sequence:
aux_runner.py --begin_step 7 ./aux_test_input/aux_tests.txt ./aux_test_processing/run.log  swiss3

```
   {
    "block": "swiss3",
    "scripts": [
        {"script": "clean_tmp", "args": ["./aux_test_processing"]},
        {"script": "swiss_to_db.py", "args": ["./aux_test_input/swiss3.zip ./aux_test_processing/swiss-import.duckdb"]},
        {"script": "epip_db_to_db.py", "args": ["./aux_test_processing/swiss-import.duckdb ./aux_test_processing/netex-database.duckdb"]},
        {"script": "epip_db_to_xml.py", "args": ["./aux_test_processing/swiss-import.duckdb ./aux_test_processing/netex-database.duckdb ./aux_test_processing/swiss3-netex.xml"]},
        {"script": "aux_assertions.py", "args": ["./aux_test_input/swiss-assertions.txt ./aux_test_processing/swiss3-netex.xml"]},
        {"script": "aux_netex_stats.py", "args": ["./aux_test_processing/swiss3-netex.xml"]},
        {"script": "netex_to_db.py", "args": ["./aux_test_processing/swiss3-netex.xml ./aux_test_processing/netex-database.duckdb"]},
        {"script": "related_explorer.py", "args": ["./aux_test_processing/netex-database.duckdb ServiceJourney random ./aux_test_processing/sj.xml"]},
        {"script": "netex_db_to_gtfs.py", "args": ["./aux_test_processing/netex-database.duckdb ./aux_test_processing/swiss3-gtfs.zip"]},
        {"script": "aux_gtfs_check.py", "args": ["./aux_test_processing/swiss3-gtfs.zip"]},
        {"script": "gtfs_show_map.py", "args": ["./aux_test_processing/swiss3-gtfs.zip ./aux_test_processing/swiss3-map.html routes"]}
        ]
  }

```

So I really just loaded: 

[swiss3-netex.zip](https://github.com/user-attachments/files/16982810/swiss3-netex.zip)
and let the related_explorer run:

[sj.zip](https://github.com/user-attachments/files/16982814/sj.zip)

**Comment by ue71603** [comment]
* responisbilitySetRef should have been processed as well as an attribute.

**Comment by skinkie** [comment]
> * It copied Line/Operator twice

My guess is that it finds two references to the Line and/or Operator, and does not deduplicate it. So I'll make sure that is does this. The more intelligent approach would be not to resolve objects which have _already_ been resolved.

For DayTypeRef I have to see what the source looks like. My guess is that this is due to _ServiceCalendar_. At this point in time the ServiceCalendar is a _single object_ (similar to StopPlace that hosts Quays). We must find some sort of way of working to be able to handle "VersionedChilds", _knowing_ that they are part of a first class object.

**Comment by skinkie** [comment]
My guess is this works as expected now. Please check and close if it does.

**Comment by ue71603** [comment]
works as far as I can see.
